const missions=[
 {category:'WARM-UP',title:'Find every digit',prompt:'A system log is full of words and numbers. Highlight each number so we can count them.',text:'Order #2048 shipped. Room 2B has 17 boxes; dock 9 is ready.',pattern:'\\d+',hint:'The backslash d token means one digit (0 through 9). Add + to collect a run of one or more digits.',idea:'A pattern is a tiny program.',copy:'It describes what to look for. The computer checks the text one piece at a time.',detail:'\\d means “one digit.” The + quantifier says “one or more of the thing before me.” Together, \\d+ finds whole runs like 2048 instead of four separate matches.',example:'Try <code>\\d</code> (without +): it finds each digit separately. Add <code>+</code> to group neighboring digits into one number.',validate:m=>m.length===4&&m.every(x=>/^\d+$/.test(x))},
 {category:'CHARACTER CLASSES',title:'Catch the email domains',prompt:'Spot the web addresses in this message. A domain is the part after the @ symbol.',text:'Write to mina@orbit.dev or help@pattern.school. No address? Ask Kai.',pattern:'[\\w.+-]+@[\\w.-]+\\.\\w+',hint:'Build it in pieces: some name characters, an @, some domain characters, a literal dot, then the ending.',idea:'A character class is a tiny “or” list.',copy:'Square brackets let you say which single characters are allowed at this position.',detail:'[abc] matches one character: a OR b OR c. A range like [a-z] means any lowercase letter. [\\w.-]+ accepts a run of word characters, dots, or hyphens.',example:'Try <code>@[\\w.-]+</code> first. Then add the name and ending. The dot in <code>\\.</code> means a real dot; a plain dot is a wildcard.',validate:m=>m.length===2&&m.every(x=>/^[\w.+-]+@[\w.-]+\.\w+$/.test(x))},
 {category:'BOUNDARIES',title:'Find whole “cat” words',prompt:'A search for cat should find the animal, not the middle of “catalog” or “educate”.',text:'A cat naps. The catalog is open; educate the kitten gently. A cat naps too.',pattern:'\\bcat\\b',hint:'A word boundary is a zero-width edge between a word character and a non-word character. Use it on both sides.',idea:'Boundaries are invisible edges.',copy:'They mark where a word starts or ends without consuming any letters.',detail:'\\b matches a position, not a character. It finds cat at a word edge, but not catalog. Python’s re is case-sensitive by default.',example:'Try <code>cat</code> alone to see the partial matches. Then add <code>\\b</code> on each side to demand word edges.',validate:m=>m.length===2&&m.every(x=>x==='cat')},
 {category:'QUANTIFIERS',title:'Spot repeated letters',prompt:'Find words with a double letter. Repetition is one of regex’s superpowers.',text:'The bookkeeper packed coffee, a glass jar, and a map for the trip.',pattern:'([a-z])\\1',hint:'A capturing group remembers what it matched. The backreference \\1 asks for that exact same character again.',idea:'Groups can remember.',copy:'Parentheses capture text so you can refer back to it later in the same pattern.',detail:'([a-z]) captures one lowercase letter as group 1. \\1 matches the same captured letter again. So ([a-z])\\1 means a doubled letter like oo or ss.',example:'Try <code>[a-z][a-z]</code> to find any two lowercase letters. Capturing + backreference narrows it to the same letter twice.',validate:m=>m.length>0&&m.every(x=>/(.)\1/i.test(x))},
 {category:'CHOICES',title:'Pick a color or a colour',prompt:'Our notes use US or UK spelling. Find either version with one compact pattern.',text:'The color palette faded. A colour test followed; then the colorist arrived.',pattern:'colou?r',hint:'The ? quantifier means “zero or one of the thing before me.” Here, u becomes optional.',idea:'Alternation is a fork in the path.',copy:'The vertical bar means “this OR that”. Parentheses keep each choice together.',detail:'(?:color|colour) is an explicit choice. A shorter solution is colou?r: the u? allows the u to be absent or present.',example:'Try <code>colou?r</code> and then <code>(?:color|colour)</code>. Both match the same spellings.',validate:m=>m.length===3&&m.every(x=>/^colou?r$/i.test(x))},
 {category:'CAPSTONE',title:'Read a simple date',prompt:'Extract dates in YYYY-MM-DD form. The month and day use two digits each.',text:'Launch: 2026-10-01. Draft: 2026-2-4. Archive: 1998-12-31.',pattern:'\\b\\d{4}-\\d{2}-\\d{2}\\b',hint:'Use exact repetition counts with {n}: four digits, hyphen, two digits, hyphen, two digits.',idea:'A quantifier can count exactly.',copy:'Curly braces set how many times the previous token repeats.',detail:'\\d{4} means exactly four digits. {2} means exactly two. This checks the shape, but not whether 2026-19-88 is a real calendar date; validation needs extra logic.',example:'Try <code>\\d+-\\d+-\\d+</code> first. Tighten each number using <code>{4}</code> and <code>{2}</code>.',validate:m=>m.length===2&&m.every(x=>/^\d{4}-\d{2}-\d{2}$/.test(x))}
];
const tokens=[['\\d','digit'],['\\w','word character'],['\\s','whitespace'],['.','any character'],['[a-z]','lowercase letter'],['+','one or more'],['*','zero or more'],['?','optional'],['{n}','exact count'],['\\b','word edge'],['|','or'],['( )','capture']];
const concepts=[['\\d','Digits','\\d matches one digit. Add + to gather a number.','Think of the pattern as a tiny scanner: it tests positions and reports the pieces that satisfy your description.'],['[a-z]','Character sets','One character chosen from a range.','Ranges include [A-Z], [0-9] and [a-z]. Put ^ first inside brackets to mean “anything except these”.'],['+  *  ?','Repeat','Say how many times something can appear.','+ means 1 or more; * means 0 or more; ? means 0 or 1. They apply to the token immediately before them.'],['( )','Groups','Keep pieces together or save a match.','(ab)+ repeats the pair “ab”. A capture group can be reused with a backreference such as \\1.'],['|','Alternation','Choose between alternatives.','cat|dog chooses either. Use parentheses when a choice is one part of a longer pattern: (cat|dog)s.'],['\\b','Boundaries','Match a word edge without consuming text.','\\bcat\\b finds whole words. The boundary is a position, so it doesn’t appear in the highlighted match.']];
let current=0,solved=new Set(),hintUsed=false, toastTimer;
const $=id=>document.getElementById(id); const patternInput=$('pattern-input');
const storyChapters=[
 {place:'CHAPTER 1 · SIGNAL BEACH',title:'THE SIGNAL IS SCRAMBLED',lines:[['Nia','The beacon mixed package numbers into ordinary text. Can we recover every number?'],['Byte','\\d means one digit. Add + to repeat it: \\d+ catches 2048 as one whole number.']],win:['Byte','Beep! Four numbers recovered. The + kept neighboring digits together as one match.']},
 {place:'CHAPTER 2 · THE MESSAGE COVE',title:'A MESSAGE IN THE BOTTLE',lines:[['Nia','A bottle washed ashore with two email addresses. We need the senders and their domains.'],['Byte','Square brackets give me a set of allowed characters. The + lets each part be as long as needed.']],win:['Nia','Two addresses found! The brackets acted like a tiny character menu at each position.']},
 {place:'CHAPTER 3 · THE WORDWOOD',title:'THE FOREST OF LOOKALIKE WORDS',lines:[['Nia','The forest sign says “cat”, but the word is hiding inside “catalog” too. Find only the animal.'],['Byte','\\b marks a word edge. Put one on each side, and “cat” must stand as its own word.']],win:['Byte','Purr-fect! Boundaries found the two whole words and ignored “catalog”.']},
 {place:'CHAPTER 4 · ECHO CANYON',title:'THE DOUBLE ECHO',lines:[['Nia','Echo Canyon repeats the last sound in some words. Can you find the doubled letters?'],['Byte','Parentheses save a letter as group 1. Then \\1 means “repeat that very same letter”.']],win:['Nia','We heard every double! A capture group remembers; the backreference plays it back.']},
 {place:'CHAPTER 5 · THE SPELLING BRIDGE',title:'TWO WAYS ACROSS',lines:[['Nia','The bridge accepts both “color” and “colour”. We need one pattern for either spelling.'],['Byte','The u is optional here. ? means zero or one of the thing just before it: colou?r.']],win:['Byte','Both spellings cross! The ? opened a path with u and another path without it.']},
 {place:'CHAPTER 6 · THE CLOCKTOWER',title:'SET THE CLOCKS',lines:[['Nia','We found dates in the archive. Keep the full dates, but leave the incomplete one behind.'],['Byte','Curly braces count repeats: \\d{4} means four digits; \\d{2} means two. We have the final clue!']],win:['Nia','The beacon is back online! You used a whole new language to bring order to the signal.']}
];
let storyPage=0,storyMode='intro';
function renderStory(){const s=storyChapters[current];$('story-location').textContent=s.place;$('dialogue-chapter').textContent=s.title;const win=storyMode==='win',briefed=storyMode==='briefed';const line=win?s.win:s.lines[storyPage];const who=line[0],speaker=who.toUpperCase();$('speaker-name').textContent=speaker;$('speaker-dot').textContent=who==='Nia'?'N':'B';$('speaker-dot').classList.toggle('byte-dot',who==='Byte');$('story-line').textContent=line[1];$('dialogue-pages').textContent=win?'CLUE FOUND':briefed?'YOUR TURN':`${storyPage+1} / ${s.lines.length}`;$('story-next').innerHTML=win?'Replay story <span>↻</span>':briefed?'Replay story <span>↻</span>':storyPage===s.lines.length-1?'Let’s solve it <span>→</span>':'Next <span>→</span>';$('nia-character').classList.toggle('talking',who==='Nia'&&!win&&!briefed);$('byte-character').classList.toggle('talking',who==='Byte'&&!win&&!briefed);document.getElementById('story-stage').classList.toggle('story-won',win)}
function safeRegex(src,flags='g'){return new RegExp(src,flags)}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getMatches(text,src,flags='g'){const re=safeRegex(src,flags),out=[];if(!re.global)re.lastIndex=0;let m,guard=0;while((m=re.exec(text))&&guard++<1000){out.push({text:m[0],start:m.index,end:m.index+m[0].length});if(m[0]==='')re.lastIndex++}return out}
function highlighted(text,matches){let html='',at=0;matches.forEach(m=>{if(m.start<at)return;html+=escapeHtml(text.slice(at,m.start))+`<mark>${escapeHtml(m.text)}</mark>`;at=m.end});return html+escapeHtml(text.slice(at))}
function renderMission(){const m=missions[current];storyPage=0;storyMode='intro';renderStory();$('level-number').textContent=String(current+1).padStart(2,'0');$('mission-category').textContent=m.category;$('mission-kicker').textContent=`MISSION ${String(current+1).padStart(2,'0')}`;$('mission-title').textContent=m.title;$('mission-prompt').textContent=m.prompt;$('hint-text').textContent=m.hint;$('hint-box').classList.toggle('hidden',!hintUsed);patternInput.value='';patternInput.placeholder='Build your pattern…';$('idea-title').textContent=m.idea;$('idea-copy').textContent=m.copy;$('idea-detail').textContent=m.detail;$('idea-detail').classList.add('hidden');$('learn-more').innerHTML='Unpack this <span>＋</span>';$('feedback').className='feedback hidden';$('next-button').classList.toggle('hidden',!solved.has(current));$('example-panel').classList.add('hidden');$('example-button').textContent='Show an example ↗';$('progress-fill').style.width=`${solved.size/missions.length*100}%`;renderTrail();runMission()}
function renderTrail(){const el=$('trail');el.innerHTML=missions.map((_,i)=>`<span class="trail-dot ${solved.has(i)?'done':i===current?'current':''}">${solved.has(i)?'✓':String(i+1).padStart(2,'0')}</span>`).join('');$('streak-count').textContent=solved.size;$('trail-caption').textContent=solved.size===missions.length?'All six clues found. Pattern master!':solved.size?`${solved.size} of 6 clues found. Keep going.`:'Every pattern starts with one clue.'}
function runMission(){const m=missions[current],src=patternInput.value;if(!src.trim()){$('regex-error').textContent='';$('stream').textContent=m.text;$('match-count').textContent='waiting for a pattern';$('feedback').className='feedback hidden';$('next-button').classList.toggle('hidden',!solved.has(current));return}try{const matches=getMatches(m.text,src);$('regex-error').textContent='';$('stream').innerHTML=highlighted(m.text,matches);$('match-count').textContent=`${matches.length} match${matches.length===1?'':'es'}`;if(m.validate(matches.map(x=>x.text))){const firstSolve=!solved.has(current);if(firstSolve){solved.add(current);renderTrail();$('progress-fill').style.width=`${solved.size/missions.length*100}%`}$('feedback').className='feedback good';$('feedback').innerHTML=`<strong>${firstSolve?'Lovely match!':'Clue found!'}</strong> ${current===missions.length-1?'You found the final clue. You now know the building blocks of a useful pattern.':'You found the target pattern. Notice how each token contributes one small rule.'}`;$('next-button').classList.remove('hidden');if(firstSolve||storyMode!=='win'){storyMode='win';renderStory();$('story-stage').scrollIntoView({behavior:'smooth',block:'nearest'})}}else{$('feedback').className='feedback hidden';$('next-button').classList.toggle('hidden',!solved.has(current))}}catch(e){$('regex-error').textContent=`Pattern error: ${e.message.replace(/^Invalid regular expression: /,'')}`;$('stream').textContent=m.text;$('match-count').textContent='check pattern';$('feedback').className='feedback try';$('feedback').textContent='A pattern needs balanced brackets and parentheses. Fix the syntax and run it again.'}}
function setView(name){document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$('view-'+name).classList.remove('hidden');window.scrollTo({top:document.querySelector('.hero').offsetHeight+30,behavior:'smooth'})}
document.querySelectorAll('.nav-link').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
$('story-next').addEventListener('click',()=>{if(storyMode==='win'||storyMode==='briefed'){storyMode='intro';storyPage=0}else if(storyPage<storyChapters[current].lines.length-1){storyPage++}else{storyMode='briefed';renderStory();$('story-next').innerHTML='Start the clue <span>→</span>';return}renderStory()});
$('hint-button').addEventListener('click',()=>{hintUsed=true;$('hint-box').classList.remove('hidden')});$('run-button').addEventListener('click',runMission);patternInput.addEventListener('input',runMission);patternInput.addEventListener('keydown',e=>{if(e.key==='Enter')runMission()});$('next-button').addEventListener('click',()=>{if(current<missions.length-1){current++;hintUsed=false;renderMission()}else{current=0;hintUsed=false;renderMission();toast('Trail complete! Play again or explore the sandbox.')}});$('learn-more').addEventListener('click',()=>{const el=$('idea-detail'),opening=el.classList.contains('hidden');el.classList.toggle('hidden');$('learn-more').innerHTML=opening?'Fold away <span>−</span>':'Unpack this <span>＋</span>'});$('example-button').addEventListener('click',()=>{const el=$('example-panel'),opening=el.classList.contains('hidden');el.innerHTML=missions[current].example;el.classList.toggle('hidden');$('example-button').innerHTML=opening?'Hide example <span>−</span>':'Show an example <span>↗</span>'});
function renderTokens(){const el=$('token-list');el.innerHTML=tokens.map(([token,label],i)=>`<button class="token-chip" data-token="${escapeHtml(token)}">${escapeHtml(token)}<span>${label}</span></button>`).join('');el.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const inp=$('sandbox-pattern'),a=inp.selectionStart,z=inp.selectionEnd;inp.value=inp.value.slice(0,a)+b.dataset.token+inp.value.slice(z);inp.focus();inp.setSelectionRange(a+b.dataset.token.length,a+b.dataset.token.length)}))}
function runSandbox(){const src=$('sandbox-pattern').value,text=$('sandbox-text').value;try{const m=getMatches(text,src);$('sandbox-error').textContent='';$('sandbox-output').innerHTML=highlighted(text,m);$('sandbox-count').textContent=`${m.length} found`}catch(e){$('sandbox-error').textContent=`Pattern error: ${e.message}`;$('sandbox-output').textContent='Correct the pattern to run it.';$('sandbox-count').textContent='—'}}$('sandbox-run').addEventListener('click',runSandbox);$('sandbox-pattern').addEventListener('keydown',e=>{if(e.key==='Enter')runSandbox()});
function renderConcepts(){const el=$('concept-grid');el.innerHTML=concepts.map((c,i)=>`<article class="concept-tile" tabindex="0" role="button" aria-expanded="false"><div class="concept-top"><span class="concept-symbol">${escapeHtml(c[0])}</span><span class="concept-expand">＋</span></div><h3>${c[1]}</h3><p>${escapeHtml(c[2])}</p><div class="concept-detail hidden">${escapeHtml(c[3])}</div></article>`).join('');el.querySelectorAll('.concept-tile').forEach(card=>{const toggle=()=>{const detail=card.querySelector('.concept-detail'),open=detail.classList.contains('hidden');detail.classList.toggle('hidden');card.setAttribute('aria-expanded',String(open));card.querySelector('.concept-expand').textContent=open?'−':'＋'};card.addEventListener('click',toggle);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})})}
$('grammar-example').addEventListener('click',()=>{const el=$('grammar-detail'),open=el.classList.contains('hidden');el.classList.toggle('hidden');el.innerHTML='Regex can describe <code>(ab)*</code> (zero or more “ab” pairs). A CFG can express balanced nesting, like <code>S → (S)S | ε</code>: <code>()</code>, <code>(())</code>, <code>()()</code>. Matching arbitrarily deep balanced pairs needs a stack; a plain regular expression does not have one. Python’s <code>re</code> is a practical pattern matcher, not a general CFG parser.';$('grammar-example').innerHTML=open?'Hide comparison <span>−</span>':'See the difference <span>↗</span>'});
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
renderMission();renderTokens();renderConcepts();
