(() => {
  const $ = (id) => document.getElementById(id);
  const player = $('player'), lily = $('lily-npc'), ravi = $('ravi-npc');
  const viewport = $('world-viewport');
  const lessons = [
    { aisle:'PRODUCE · AISLE 01', title:'The shopping list', left:'FRUIT & VEG', right:'WEIGH & GO', caption:'First, Oscar needs the right number of apples.', concept:'Digits and “one or more”', pattern:String.raw`\d+`, meaning:'\\d matches one digit (0–9). The + means “one or more” of the thing just before it. Together, they find a whole run of digits.', examples:['3 apples','24 pears','007 stickers'], lines:[['Oscar','THE SHOPPER','I need to pick up 24 apples, but the price labels list all kinds of numbers. How can we spot the quantities?'],['Lily','STORE GUIDE','Ask Ravi in produce. Tell him we need the digit runs, not the words around them.'],['Ravi','PRODUCE SPECIALIST','Use \\d+ . The backslash makes d mean a digit; + repeats it. It finds 24 in “24 apples” and 007 in “007 stickers”.'],['Oscar','THE SHOPPER','So \\d alone would catch one digit, while \\d+ keeps going through the number?'],['Ravi','PRODUCE SPECIALIST','Exactly. In Python: re.findall(r"\\d+", text). It returns every matching number as text.']] },
    { aisle:'DELI · AISLE 02', title:'A note from the supplier', left:'MESSAGES', right:'SUPPLIER MAIL', caption:'A tiny dot has a big job in an email address.', concept:'Character sets, word characters, and literal dots', pattern:String.raw`[\w.-]+@[\w.-]+\.\w+`, meaning:'A character set [...] allows one character from a small list. \\w means a word character (letters, digits, underscore). A dot is normally a wildcard, so \\. means an actual dot.', examples:['mina@orbit.dev','help@pattern.school','not-an-address'], lines:[['Oscar','THE SHOPPER','The deli needs me to email Mina. I can see her address on this note, but which part tells me the web domain?'],['Lily','STORE GUIDE','The @ is our landmark. Ravi can show you how to describe the characters around it.'],['Ravi','DELI SPECIALIST','A practical address pattern is [\\w.-]+@[\\w.-]+\\.\\w+. The brackets allow letters, digits, dot, underscore, or hyphen in each part.'],['Oscar','THE SHOPPER','Why is the dot written \\., but the @ is plain?'],['Ravi','DELI SPECIALIST','Dot means “any character” in regex. Escaping it with a backslash asks for a real dot. @ has no special regex meaning, so it stays plain. Python: re.findall(pattern, text).']] },
    { aisle:'PET FOOD · AISLE 03', title:'Find the whole word “cat”', left:'PET LABELS', right:'WORD SEARCH', caption:'The scanner should find “cat”, not the middle of “catalog”.', concept:'Boundaries and whole words', pattern:String.raw`\bcat\b`, meaning:'\\b is a zero-width word boundary: a position between a word character and a non-word character (or the start/end). It consumes no text. Put it around cat to ask for that whole word.', examples:['cat food → match','catalog → no match','a cat! → match'], lines:[['Oscar','THE SHOPPER','I’m buying cat food. Can we find labels that say “cat” without catching words such as “catalog”?'],['Lily','STORE GUIDE','Let’s ask Ravi about where a word starts and ends. That invisible edge is useful.'],['Ravi','PET CARE SPECIALIST','Use \\bcat\\b. The two \\b markers match word edges, not letters. So “cat food” matches, while “catalog” does not.'],['Oscar','THE SHOPPER','It matches a boundary but doesn’t appear in the result?'],['Ravi','PET CARE SPECIALIST','Right. A boundary is a position, not a character. In Python, re.search(r"\\bcat\\b", label, re.I) also ignores capitalization.']] },
    { aisle:'BAKERY · AISLE 04', title:'Spot repeated letters', left:'BAKED GOODS', right:'LABEL CHECK', caption:'One capture can remember a letter and look for it again.', concept:'Capturing groups and backreferences', pattern:String.raw`(\w)\1`, meaning:'Parentheses capture what a subpattern matches. \\1 means “match the same text captured by group 1 again.” This detects adjacent repeated word characters, such as oo in cookie.', examples:['cookie → oo','coffee → ff','bread → no match'], lines:[['Oscar','THE SHOPPER','The bakery has a sign that says “coookie”. I want the repeated letters so we can fix the label.'],['Lily','STORE GUIDE','Ravi knows a pattern that remembers a letter and checks whether it appears twice.'],['Ravi','BAKERY SPECIALIST','Use (\\w)\\1. The parentheses capture one word character; \\1 repeats that exact character. It finds oo in cookie and ff in coffee.'],['Oscar','THE SHOPPER','Would (\\w)\\w find two letters too?'],['Ravi','BAKERY SPECIALIST','It would find any two word characters, even different ones. The backreference is what requires the second character to equal the first. In Python, groups are returned with findall.']] },
    { aisle:'CHILLER · AISLE 05', title:'Colour or color?', left:'DRINKS', right:'SPELLING CHECK', caption:'One pattern can accept either spelling.', concept:'Optional characters and alternatives', pattern:String.raw`colou?r|color`, meaning:'? makes the item immediately before it optional (zero or one). The | symbol means “or”: the expression on its left or right can match. Parentheses can group alternatives when needed.', examples:['color → match','colour → match','colouur → no match'], lines:[['Oscar','THE SHOPPER','The drinks list uses both “color” and “colour”. I want one search that accepts either spelling.'],['Lily','STORE GUIDE','Ravi can show us how to make one letter optional.'],['Ravi','CHILLER SPECIALIST','Use colou?r. The u? means the u can appear zero or one time, so both color and colour match.'],['Oscar','THE SHOPPER','And the vertical bar | means “or”, right?'],['Ravi','CHILLER SPECIALIST','Yes. For example, colou?r|flavour matches either spelling family. Use parentheses to control alternatives: (cat|dog) food.']] },
    { aisle:'CHECKOUT · AISLE 06', title:'Check the date format', left:'EXPIRY LABELS', right:'CHECKOUT', caption:'A pattern checks shape; a parser checks meaning.', concept:'Exact repetition and the limits of regex', pattern:String.raw`\b\d{4}-\d{2}-\d{2}\b`, meaning:'{n} repeats the previous item exactly n times. This pattern checks a YYYY-MM-DD shape. A regex can check the shape, but calendar validity (like whether February has 30 days) needs additional logic.', examples:['2026-10-01 → shape matches','2026-02-30 → shape matches, invalid date','26-10-01 → no match'], lines:[['Oscar','THE SHOPPER','Before I check out, I need to find dates written like 2026-10-01 on the packages.'],['Lily','STORE GUIDE','Ravi can check the format. But we should also ask whether a matching shape is a real date.'],['Ravi','CHECKOUT SPECIALIST','Use \\b\\d{4}-\\d{2}-\\d{2}\\b. The braces mean exact repetition: four digits, dash, two digits, dash, two digits.'],['Oscar','THE SHOPPER','Does it prove that the date exists?'],['Ravi','CHECKOUT SPECIALIST','No: 2026-02-30 has the right shape but isn’t a calendar date. Regex recognizes regular patterns. Nested, recursively balanced parentheses need a context-free grammar and a stack.'],['Lily','STORE GUIDE','A CFG rule such as S → (S)S | ε can describe balanced parentheses at any depth. Regex is excellent for local patterns; a parser is the right tool for recursive structure.']] }
  ];
  const notes = [
    ['Digits and repetition', String.raw`\d+`, 'Find one or more digits. + repeats the previous token at least once.', 'IDs: A7, 25, 003'],
    ['Character sets', String.raw`[abc]  [a-z]  [^0-9]`, 'A bracket set matches one character from the listed set or range. A leading ^ inside the brackets negates the set.', 'b in [abc] · q in [a-z] · X in [^0-9]'],
    ['Word characters and dots', String.raw`\w+  \.`,'\\w matches letters, digits, and underscore. Dot matches any character; \\. matches a literal dot. Python’s Unicode behavior may include more letters.', 'user_name · domain.example'],
    ['Word boundaries', String.raw`\bcat\b`, 'Matches cat as a whole word. The boundary is a position, not a character.', 'cat ✓ · catalog ✗ · bobcat ✗'],
    ['Captures and backreferences', String.raw`(\w)\1`, 'Parentheses capture a match. \\1 refers to the text captured by the first group.', 'll · oo · 77'],
    ['Optional and “or”', String.raw`colou?r  (cat|dog)`, '? means zero or one of the previous token. | chooses between alternatives.', 'color / colour · cat food / dog food'],
    ['Exact repetition', String.raw`\d{4}-\d{2}-\d{2}`, '{n} repeats the preceding token exactly n times; {m,n} means between m and n times.', '2026-10-01'],
    ['Regex or CFG?', 'Regular expression ≠ recursive grammar', 'Regex describes regular languages, which can be recognized with finite memory. Balanced parentheses at arbitrary depth need recursive structure and a stack, commonly described by a CFG.', 'S → (S)S | ε generates (), (()), ()()']
  ];
  let chapter = 0, pos = {x:18,y:80}, target = 'lily', currentLines = [], lineIndex = 0;
  let playing = false, paused = false, timer = null, holding = null, toastTimer = null;
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
  function setPos(x,y){pos.x=clamp(x,7,93);pos.y=clamp(y,58,90);player.style.left=pos.x+'%';player.style.top=pos.y+'%';player.style.zIndex=String(Math.round(4+pos.y/10));}
  function npcPos(which){const node=which==='lily'?lily:ravi;return {x:parseFloat(node.style.left)|| (which==='lily'?35:67), y:parseFloat(node.style.top)||76};}
  function distance(a,b){return Math.hypot((a.x-b.x)*.8,a.y-b.y);}
  function nearTarget(){return distance(pos,npcPos(target))<17;}
  function setTarget(which){target=which; const node=which==='lily'?lily:ravi; $('target-marker').style.left=node.style.left|| (which==='lily'?'35%':'67%');$('target-marker').style.top=node.style.top||'76%';$('target-marker').classList.remove('hidden');$('target-label').textContent=which==='lily'?'Lily':'Ravi';$('interact-label').textContent=nearTarget()?'Talk to '+(which==='lily'?'Lily':'Ravi'):'Walk to '+(which==='lily'?'Lily':'Ravi');$('walk-prompt-text').textContent=nearTarget()?'Press E to talk to '+(which==='lily'?'Lily':'Ravi'):'Walk over to '+(which==='lily'?'Lily':'Ravi');$('walk-prompt').classList.toggle('hidden',nearTarget());$('dialogue-status').textContent='Walk up to '+(which==='lily'?'Lily':'Ravi')+' to continue'; lily.classList.toggle('selected-character',which==='lily');ravi.classList.toggle('selected-character',which==='ravi');}
  function move(dx,dy){if($('notes-modal').classList.contains('hidden')===false||!$('ending-overlay').classList.contains('hidden'))return;const step=holding?1.05:2.5;setPos(pos.x+dx*step,pos.y+dy*step);player.classList.add('walking');clearTimeout(move.walkTimer);move.walkTimer=setTimeout(()=>player.classList.remove('walking'),180);updatePrompt();}
  function updatePrompt(){const npc=target==='lily'?lily:ravi, p=npcPos(target);const close=nearTarget();$('walk-prompt').classList.toggle('hidden',close||target==='exit');$('walk-prompt-text').textContent=close?'Press E to talk to '+(target==='lily'?'Lily':'Ravi'):'Walk over to '+(target==='lily'?'Lily':'Ravi');$('interact-label').textContent=close?'Talk to '+(target==='lily'?'Lily':'Ravi'):(target==='exit'?'Enter next aisle':'Walk to '+(target==='lily'?'Lily':'Ravi'));$('target-marker').style.left=target==='exit'?'92%':(p.x+'%');$('target-marker').style.top=target==='exit'?'75%':(p.y+'%');}
  function showToast(s){const t=$('toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2400);}
  function speaker(name,role){$('speaker-name').textContent=name;$('speaker-role').textContent=role;$('speaker-avatar').textContent=name.slice(0,1);[player,lily,ravi].forEach(n=>n.classList.remove('speaking'));const node=name==='Oscar'?player:name==='Lily'?lily:ravi;node.classList.add('speaking');setTimeout(()=>node.classList.remove('speaking'),1000);}
  function dots(){const root=$('conversation-dots');root.innerHTML='';currentLines.forEach((_,i)=>{const d=document.createElement('i');if(i<lineIndex)d.classList.add('done');root.appendChild(d)});}
  function renderLine(){if(lineIndex>=currentLines.length){finishScene();return}const [name,role,text]=currentLines[lineIndex];speaker(name,role);$('dialogue-text').textContent=text;$('dialogue-status').textContent='Story playing · '+(lineIndex+1)+' of '+currentLines.length;$('live-led').classList.add('active');$('annotation-button').disabled=false;$('lesson-note').classList.add('hidden');dots();if(playing&&!paused)timer=setTimeout(nextLine,6800);}
  function nextLine(){clearTimeout(timer);if(!playing)return;lineIndex++;if(lineIndex>=currentLines.length){renderLine();return}renderLine();}
  function beginScene(who){clearTimeout(timer);$('walk-prompt').classList.add('hidden');$('dialogue-dock').classList.remove('collapsed');$('dialogue-text').textContent='';$('lesson-note').classList.add('hidden');$('live-led').classList.remove('active');const L=lessons[chapter];
    if(who==='lily'){currentLines=L.lines.filter(v=>v[0]==='Oscar'||v[0]==='Lily');setTarget('lily')}else{currentLines=L.lines.filter(v=>v[0]==='Ravi');}
    lineIndex=0;playing=false;paused=false;$('story-start').disabled=false;$('story-pause').disabled=true;$('story-stop').disabled=false;$('dialogue-status').textContent='Ready · press Start';$('dialogue-text').textContent='';dots();$('annotation-button').disabled=true;showToast(who==='lily'?'Lily has a plan for this aisle.':'Ravi is ready to explain the pattern.');
    $('story-start').onclick=()=>startPlayback();$('story-pause').onclick=()=>togglePause();$('story-stop').onclick=()=>stopPlayback();
  }
  function startPlayback(){if(!currentLines.length)return;if(lineIndex>=currentLines.length)lineIndex=0;playing=true;paused=false;$('story-start').disabled=true;$('story-pause').disabled=false;$('story-pause').innerHTML='<span>Ⅱ</span> Pause';$('dialogue-status').textContent='Story playing';renderLine();}
  function togglePause(){if(!playing)return;if(paused){paused=false;$('story-pause').innerHTML='<span>Ⅱ</span> Pause';$('dialogue-status').textContent='Story playing';renderLine()}else{paused=true;clearTimeout(timer);$('story-pause').innerHTML='<span>▶</span> Resume';$('dialogue-status').textContent='Story paused';$('live-led').classList.remove('active')}}
  function stopPlayback(){clearTimeout(timer);playing=false;paused=false;lineIndex=0;$('story-start').disabled=false;$('story-pause').disabled=true;$('story-pause').innerHTML='<span>Ⅱ</span> Pause';$('story-stop').disabled=true;$('dialogue-status').textContent='Stopped · press Start to replay';$('live-led').classList.remove('active');$('lesson-note').classList.add('hidden');dots();if(currentLines.length){const [n,r,t]=currentLines[0];speaker(n,r);$('dialogue-text').textContent=t}}
  function finishScene(){playing=false;paused=false;clearTimeout(timer);$('story-start').disabled=false;$('story-pause').disabled=true;$('story-stop').disabled=true;$('live-led').classList.remove('active');$('dialogue-status').textContent='Scene complete';$('dialogue-text').textContent=target==='lily'?'Lily has pointed Oscar toward the specialist. Walk over to Ravi to continue the story.':'You’ve reached the end of this aisle’s story. Walk to the glowing gate to keep exploring.';dots();$('annotation-button').disabled=false;if(target==='lily'){setTarget('ravi');showToast('Story beat complete — walk over to Ravi.')}else{target='exit';$('target-label').textContent='Next aisle';$('target-marker').style.left='92%';$('target-marker').style.top='75%';$('exit-gate').classList.remove('hidden');$('interact-label').textContent='Walk to next aisle';$('walk-prompt-text').textContent='Walk to the glowing gate';$('walk-prompt').classList.remove('hidden');}}
  function interact(){if(target==='exit'){if(pos.x>79){nextChapter()}else showToast('Walk toward the glowing gate at the far end.');return}if(!nearTarget()){const p=npcPos(target),dx=p.x-pos.x,dy=p.y-pos.y;move(Math.sign(dx),Math.sign(dy));showToast('A little closer to '+(target==='lily'?'Lily':'Ravi')+'.');return}beginScene(target);}
  function nextChapter(){chapter++;if(chapter>=lessons.length){$('ending-overlay').classList.remove('hidden');return}loadChapter();showToast('New aisle unlocked!');}
  function loadChapter(){const L=lessons[chapter];$('chapter-title').textContent=L.title;$('chapter-count').textContent=String(chapter+1).padStart(2,'0')+' / 06';$('quest-progress-fill').style.width=((chapter+1)/lessons.length*100)+'%';$('aisle-name').textContent=L.aisle;$('shelf-header-left').textContent=L.left;$('shelf-header-right').textContent=L.right;$('scene-caption').textContent=L.caption;$('ravi-npc').classList.remove('hidden');$('lily-npc').classList.remove('hidden');$('exit-gate').classList.add('hidden');setPos(12,81);setTarget('lily');currentLines=[];lineIndex=0;playing=false;$('dialogue-status').textContent='Walk up to Lily to begin';$('dialogue-text').textContent='Oscar has a new shopping problem. Walk over to Lily, then press E to hear the next part of their story.';$('story-start').disabled=true;$('story-pause').disabled=true;$('story-stop').disabled=true;$('annotation-button').disabled=true;$('lesson-note').classList.add('hidden');dots();}
  function showAnnotation(){if(!currentLines.length)return;const L=lessons[chapter];$('note-label').textContent=L.concept.toUpperCase();$('note-text').textContent=L.meaning;$('note-pattern').textContent=L.pattern;$('note-pattern').classList.remove('hidden');$('note-examples').textContent='Examples: '+L.examples.join(' · ');$('lesson-note').classList.remove('hidden');}
  function openNotes(){const grid=$('notes-grid');grid.innerHTML='';notes.forEach(([title,pattern,desc,examples])=>{const card=document.createElement('article');card.className='note-card';const h=document.createElement('h3');h.textContent=title;const code=document.createElement('code');code.textContent=pattern;const p=document.createElement('p');p.textContent=desc;const ex=document.createElement('p');ex.className='note-examples';ex.textContent=examples;card.append(h,code,p,ex);grid.append(card)});$('notes-modal').classList.remove('hidden');}
  $('notes-open').addEventListener('click',openNotes);$('notes-close').addEventListener('click',()=>$('notes-modal').classList.add('hidden'));$('notes-modal').addEventListener('click',e=>{if(e.target===$('notes-modal'))$('notes-modal').classList.add('hidden')});$('ending-notes').addEventListener('click',openNotes);$('restart-trip').addEventListener('click',()=>{$('ending-overlay').classList.add('hidden');chapter=0;loadChapter()});$('annotation-button').addEventListener('click',showAnnotation);$('dock-collapse').addEventListener('click',()=>$('dialogue-dock').classList.toggle('collapsed'));$('interact-button').addEventListener('click',interact);lily.addEventListener('click',()=>{if(target==='lily')interact();else showToast('Lily is not the next person to speak. Follow the glowing marker.')});ravi.addEventListener('click',()=>{if(target==='ravi')interact();else showToast('Follow the glowing marker to meet Ravi.')});
  const keys={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]};document.addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(keys[k]){e.preventDefault();move(...keys[k])}else if(k==='e'||k==='Enter'){if(!e.repeat)interact()}else if(k==='Escape'){ $('notes-modal').classList.add('hidden');$('ending-overlay').classList.add('hidden')}});
  document.querySelectorAll('[data-move]').forEach(btn=>{const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};btn.addEventListener('pointerdown',e=>{e.preventDefault();holding=btn.dataset.move;move(...dirs[holding]);clearInterval(btn._repeat);btn._repeat=setInterval(()=>move(...dirs[holding]),130)});['pointerup','pointerleave','pointercancel'].forEach(ev=>btn.addEventListener(ev,()=>{clearInterval(btn._repeat);holding=null}))});
  function animateWorld(){if(target==='exit'&&pos.x>80&&$('ending-overlay').classList.contains('hidden')){nextChapter()}if(target!=='exit'&&nearTarget()){$('interact-label').textContent='Talk to '+(target==='lily'?'Lily':'Ravi');$('walk-prompt-text').textContent='Press E to talk to '+(target==='lily'?'Lily':'Ravi');$('walk-prompt').classList.remove('hidden')}requestAnimationFrame(animateWorld)}
  // Character positions are relative to the scene so the walking scene scales cleanly.
  lily.style.left='35%';lily.style.top='76%';ravi.style.left='67%';ravi.style.top='76%';setPos(16,80);setTarget('lily');
  $('story-start').disabled=true;$('story-pause').disabled=true;$('story-stop').disabled=true;$('annotation-button').disabled=true;
  setTimeout(()=>{ $('dialogue-dock').classList.remove('collapsed') },0);requestAnimationFrame(animateWorld);
})();
